[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "olist-customer-intelligence"
version = "0.1.0"
description = "End-to-end Data Engineering platform using Databricks and the Olist dataset"
requires-python = ">=3.11"

dependencies = [
    "requests",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = [
    "src"
]

testpaths = [
    "tests"
]